config/routes.rb
  Rails.application.routes.draw do
  root 'dashboard#index'

  get '/admin', to: 'admin/users#index'
  get '/dashboard', to: 'dashboard#index'

  #page
  get 'page/home'
  get 'page/about'
  get 'page/contact'

  #diagnostics
  get 'healthcheck', to: 'diagnostics#healthcheck'

  # Admin
  namespace :admin do
      resources :users do
        member do
          get 'get_user_roles'
        end
      end

      resources :products do
        post 'import'
        resources :contributions, shallow: true do
          collection do

            post 'permissions'
            post 'update_permissions'
            post 'destroy_permissions'
          end
        end

        resources :modulees, path: 'modules'
        resources :flashcards do
          member do
            get 'update_flashcard_item_position'
          end
        end
        resources :htmls, path: 'html'
        resources :quizzes do
          get 'download'
          post 'upload'
        end
        resources :media
      end

      resources :contents do
        collection do
          get 'update_content_position'
        end

        post 'usercontentssave'
        post 'usercontentsupdate'
        resources :contributions, shallow: true do
          collection do
            post 'permissions'
            post 'update_permissions'
            post 'destroy_permissions'

          end
        end

      end

      resources :roles, only: [:show]
  end

  resources :products, only: [:index, :show]

  # Devise
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  # Ckeditor
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  acts_as :content

  has_many :flashcard_items, dependent: :destroy
  accepts_nested_attributes_for :flashcard_items, reject_if: :all_blank, allow_destroy: true

  def items
    flashcard_items
  end
end

app/controllers/admin/flashcards_controller.rb
class Admin::FlashcardsController < Admin::BaseController
  before_action :set_flashcard, only: [:show, :edit, :update, :destroy]
  before_action :set_product, except: [:destroy]
  before_action :set_content, except: [:destroy]

  def show
    @flashcard_items = @flashcard.items.rank(:row_order)
  end

  def new
    @flashcard = Flashcard.new(product_id: @product.id) if @product.present?
    @flashcard ||= Flashcard.new
  end
  
  def edit
  end

  def create
    @flashcard = Flashcard.new(flashcard_params)

    if @flashcard.save
      redirect_to admin_product_flashcard_url(@product, @flashcard), notice: 'Flashcard Content was successfully created'
    else
      # persist content if the form validation fails
      @content ||= Content.find(flashcard_params[:parent_id].to_i) if flashcard_params[:parent_id].present?
      
      render action: :new
    end
  end

  def update
    if @flashcard.update(flashcard_params)
      redirect_to admin_product_flashcard_url(@product, @flashcard), notice: 'Flashcard Content was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
  end

  def update_flashcard_item_position
    # TODO: Not cool, do something about the following 2 lines of code.
    flashcard_item = flashcard_params[:flashcard_items_attributes].first if flashcard_params[:flashcard_items_attributes].present?
    flashcard_item = flashcard_item[1] if flashcard_item.present?

    if flashcard_item.present? && flashcard_item[:id].to_i > 0
      fitem = FlashcardItem.find(flashcard_item[:id])
      fitem.row_order_position = flashcard_item[:row_order_position]
      fitem.save
    end

    render nothing: true
  end

  private

  def set_flashcard
    @flashcard ||= Flashcard.find(params[:id])
  end

  def set_product
    @product ||= Product.find(params[:product_id])
  end

  def set_content
    @content ||= Content.find(params[:content_id]) if params[:content_id].present?
  end

  def flashcard_params
    params.require(:flashcard).permit(:title, :parent_id, :product_id, flashcard_items_attributes: [:id, :front, :back, :row_order_position, :_destroy])
  end

end

app/views/admin/flashcards/_flashcard_item_fields.html.haml
.row.nested-fields
  .col-md-5.form-group.field
    = f.cktext_area :front, class: 'form-control', ckeditor: { toolbar: :mini }
  .col-md-5.form-group.field
    = f.cktext_area :back, class: 'form-control', ckeditor: { toolbar: :mini }
  .col-md-2
    = link_to_remove_association "<span class='glyphicon glyphicon-remove'></span> Delete".html_safe, f, class: 'btn btn-default btn-sm'
%br

app/views/admin/flashcards/_form.html.haml
.h1
  Flashcard Deck
= form_for [:admin, @product, @flashcard] do |f|
  .row
    .col-md-6
      = errors_for(@flashcard)

      = f.hidden_field :product_id, value: @product.id
      = f.hidden_field :parent_id, value: @content.id if @content.present?
      .form-group
        %label= f.label :title
        = f.text_field :title, class: 'form-control'

  .h4 Cards

  - if @flashcard.flashcard_items.present?
    .row
      .col-md-5
        .h5 Front
      .col-md-5
        .h5 Back

  = f.fields_for :flashcard_items do |flashcard_item|
    = render 'flashcard_item_fields', f: flashcard_item
  .form-group.links
    = link_to_add_association 'New Flashcard Item', f, :flashcard_items, class: 'btn btn-default btn-sm'
    = f.submit class: 'btn btn-sm btn-default'

app/views/admin/flashcards/show.html.haml
.h2
  Flashcard Deck
  %small
    = @flashcard.title
%br
.h4 Cards
.help-block (Click on the tiles to flip sides)
.row
  .col-md-6
    %ul#sortable_flashcard_items
      - @flashcard_items.each_with_index do |item, index|
        %li{ "data-flashcard-item-id": item.id }
          .well.flashcard-item-view
            .h6
              .label
                FRONT
              = raw(item.front)
            .h6.hidden
              .label
                BACK
              = raw(item.back)

.row
  .col-md-6
    .btn.btn-default.btn-sm
      = link_to('Back', admin_product_path(@product))
    .btn.btn-default.btn-sm
      = link_to('Edit', edit_admin_product_flashcard_path(@product, @flashcard))