config/routes.rb
  Rails.application.routes.draw do
  root 'dashboard#index'

  get '/admin', to: 'admin/users#index'
  get '/dashboard', to: 'dashboard#index'

  #page
  get 'page/home'
  get 'page/about'
  get 'page/contact'

  #diagnostics
  get 'healthcheck', to: 'diagnostics#healthcheck'

  # Admin
  namespace :admin do
      resources :users do
        member do
          get 'get_user_roles'
        end
      end

      resources :products do
        post 'import'
        resources :contributions, shallow: true do
          collection do

            post 'permissions'
            post 'update_permissions'
            post 'destroy_permissions'
          end
        end

        resources :modulees, path: 'modules'
        resources :flashcards do
          member do
            get 'update_flashcard_item_position'
          end
        end
        resources :htmls, path: 'html'
        resources :quizzes do
          get 'download'
          post 'upload'
        end
        resources :media
      end

      resources :contents do
        collection do
          get 'update_content_position'
        end

        post 'usercontentssave'
        post 'usercontentsupdate'
        resources :contributions, shallow: true do
          collection do
            post 'permissions'
            post 'update_permissions'
            post 'destroy_permissions'

          end
        end

      end

      resources :roles, only: [:show]
  end

  resources :products, only: [:index, :show]

  # Devise
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  # Ckeditor
  mount Ckeditor::Engine => '/ckeditor'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
      if current_user
        @products = Product.where(visibility: [Product::VISIBILITY_ALL, Product::VISIBILITY_REGISTERED_USERS])
        @my_products = current_user.subscribed_products || []
      else
        @products = Product.where(visibility: Product::VISIBILITY_ALL)
      end
  end
end

app/views/dashboard/index.html.haml
- if @my_products.present?
  .row
    %h3 My Products
  .row
    - @my_products.each do |product|
      .col-md-4.col-sm-6
        .thumbnail
          = image_tag('http://lorempixel.com/512/512')
          .caption
            %h3
              = product.title
            %p Lorem ipsum
            %p
              = link_to 'Launch', product_url(product), class: 'btn btn-primary'
- if @products.present?
  .row
    %h3 Available Products
  .row
    - @products.each do |product|
      .col-md-4.col-sm-6
        .thumbnail
          = image_tag('http://lorempixel.com/512/512')
          .caption
            %h3
              = product.title
            %p Lorem ipsum
            %p
              = link_to 'Buy', product_url(product), class: 'btn btn-primary'