config/routes.rb
  Rails.application.routes.draw do
  root 'dashboard#index'

  get '/admin', to: 'admin/users#index'
  get '/dashboard', to: 'dashboard#index'

  #page
  get 'page/home'
  get 'page/about'
  get 'page/contact'

  #diagnostics
  get 'healthcheck', to: 'diagnostics#healthcheck'

  # Admin
  namespace :admin do
      resources :users do
        member do
          get 'get_user_roles'
        end
      end

      resources :products do
        post 'import'
        resources :contributions, shallow: true do
          collection do

            post 'permissions'
            post 'update_permissions'
            post 'destroy_permissions'
          end
        end

        resources :modulees, path: 'modules'
        resources :flashcards do
          member do
            get 'update_flashcard_item_position'
          end
        end
        resources :htmls, path: 'html'
        resources :quizzes do
          get 'download'
          post 'upload'
        end
        resources :media
      end

      resources :contents do
        collection do
          get 'update_content_position'
        end

        post 'usercontentssave'
        post 'usercontentsupdate'
        resources :contributions, shallow: true do
          collection do
            post 'permissions'
            post 'update_permissions'
            post 'destroy_permissions'

          end
        end

      end

      resources :roles, only: [:show]
  end

  resources :products, only: [:index, :show]

  # Devise
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  # Ckeditor
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/product.rb
class Product < ApplicationRecord
  VISIBILITY_ALL = "All"
  VISIBILITY_REGISTERED_USERS = "Registered Users"
  VISIBILITY_PRIVILEGED_USERS = "Privileged Users"

  validates :title, presence: true, uniqueness: true
  validates :visibility, presence: true

  has_many :permissions, dependent: :destroy
  has_many :users, through: :permissions
  accepts_nested_attributes_for :permissions, reject_if: :all_blank, allow_destroy: true

  has_many :user_subscriptions, dependent: :destroy
  has_many :subscribed_users, through: :user_subscriptions, class_name: 'User', foreign_key: :user_id, source: :user

  has_many :contents, dependent: :destroy
  accepts_nested_attributes_for :contents, reject_if: :all_blank, allow_destroy: true

  has_many :product_assets

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path, packed: false, file_warning: :ignore)
    when ".xls" then Roo::Excel.new(file.path, packed: false, file_warning: :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, packed: false, file_warning: :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_content_types, only: [:show, :new, :edit]

  def index
    if current_user.is_admin?
      @products = Product.all
    else
      @products = current_user.products
    end
  end

  def import
     rowarray = Hash.new
     values=Array.new
     spreadsheet = Product.open_spreadsheet(params[:file])
     header = spreadsheet.row(1)
     (2..spreadsheet.last_row).each do |i|
       rowarray = Hash[[header, spreadsheet.row(i)].transpose]
        #@rowarray = rowarray
        values << rowarray

     end
     session[:rowarray] = rowarray
     session[:array] = values
       redirect_to :back, notice: "Records imported."
  end

  def show
    @contents = Content.rank(:row_order).where(:product_id => params[:id]).roots
    @rowarray = session[:rowarray]
    @values = session[:array]
  end

  def new
    @product = Product.new
  end

  def edit
    @contents = Content.all
    @product_managers = @product.users.pluck(:email) unless @product.users.empty?
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_content_types
      @content_types = Content::CONTENT_TYPES
    end


    # Never trust parameters from the scary internet, only allow the white list through.

    def product_params
      params.fetch(:product).permit(:title, :visibility,
        managers: [],
        permissions_attributes: [:id, :product_id, :user_id, :role_id, :_destroy, contents: []])
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]
  layout 'product'

  def index
    @products = user_signed_in? ? current_user.products : []
  end

  def show

  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper

end

app/helpers/products_helper.rb
module ProductsHelper
  # Get all the non-admin users who aren't contributing to this product
  def non_contributing_users pid
    users = User.non_admins
    users.present? ? users.pluck(:username, :id) : []
  end

  def contents_to_array perm_id
    # TODO: This is a tmp solution. Find a better way.
    perm = Permission.where(id: perm_id) if perm_id.to_i > 0
    contents = perm.first.contents if perm.present?
    
    contents
  end
end

app/views/admin/products/_audio.html.haml
.panel.panel-default
  .panel-heading
    = audio.title
    .pull-right
      .btn.btn-default.btn-xs
        Edit
  .panel-body
    %p
      audio details go here

app/views/admin/products/_flashcard_fields.html.erb
<% f.object = f.object.specific if f.object.specific.instance_of? Flashcard %>

<div class="col-md-12" style=<%= "display: hidden".html_safe if cannot? :read, f.object.content %>>
  <div class="row flashcard_fields">
    <%= f.hidden_field :actable_type, value: 'Flashcard' %>
    <%= f.hidden_field :parent_id %>
    
    <div class="form-group col-md-10">
      <%= f.label :name, class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group col-md-2">
      <%= link_to_remove_association "<span class='glyphicon glyphicon-minus' aria-hidden='true'></span>".html_safe, f, class: "remove_fields btn btn-sm btn-danger", data: { confirm: 'Are you sure?' }, wrapper_class: 'flashcard_fields'  %>
    </div>
  </div>
</div>

app/views/admin/products/_form.html.haml
.row
  = form_for [:admin, @product], html: { class: 'form col-md-6' } do |f|
    = errors_for(@product)
    
    .form-group
      = f.label :title, class: 'control-label'
      = f.text_field :title, class: 'form-control'

    .form-group
      = f.label :visibility, class: 'control-label'
      = f.select :visibility, options_for_select(["All", "Registered Users", "Privileged Users"], @product.visibility), {}, { class: 'form-control' }

    %hr

    .h4
      Permissions
      %br
      %br
      = f.fields_for :permissions do |permission|
        / render permissions which don't relate to current user
        = render 'permission_fields', f: permission if permission.object.user_id != current_user.id
      
      .form-group.links
        = link_to_add_association 'New Permissions', f, :permissions, class: 'btn btn-default btn-sm'    

    .form-group
      = link_to 'Back', admin_products_path(@product), class: 'btn btn-sm btn-primary'
      = f.submit class: 'btn btn-sm btn-success'

app/views/admin/products/_html.html.haml
.panel.panel-default
  .panel-heading
    = link_to html.title, admin_product_html_path(@product, html.actable_id)
    .pull-right
      .btn.btn-default.btn-xs
        = link_to('edit', edit_admin_product_html_path(@product, html.actable_id))
  .panel-body
    = #raw(html.html_source)

app/views/admin/products/_html_fields.html.erb
<% f.object = f.object.specific if f.object.specific.instance_of? Html %>

<div class="col-md-12" style=<%= "display: hidden".html_safe if cannot? :read, f.object.content %>>
  <div class="row html_fields">
    <%= f.hidden_field :actable_type, value: 'Html' %>
    <%= f.hidden_field :parent_id %>

    <div class="form-group col-md-10">
      <%= f.label :name, class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group col-md-2">
      <%= link_to_remove_association "<span class='glyphicon glyphicon-minus' aria-hidden='true'></span>".html_safe, f, class: "remove_fields btn btn-sm btn-danger", data: { confirm: 'Are you sure?' }, wrapper_class: 'html_fields'  %>
    </div>

    <div class="form-group col-md-10">
      <%= f.label :description, class: 'control-label' %>
      <%= f.cktext_area :description, class: 'form-control' %>
    </div>
  </div>
</div>

app/views/admin/products/_media.html.haml
.panel.panel-default
  .panel-heading
    %span.h5
      = link_to media.title, admin_product_media_path(@product, media.actable_id)
    .label.label-default
      = media.specific.local_type.capitalize
    .pull-right
      .btn.btn-default.btn-xs
        = link_to('edit', edit_admin_product_media_path(@product, media.actable_id))
  .panel-body
    = render partial: "/admin/media/media_type", locals: { media: media.specific }

app/views/admin/products/_module_fields.html.erb
<% f.object = f.object.specific if f.object.specific.instance_of? Modulee %>

<div class="col-md-12" style=<%= "display: hidden".html_safe if cannot? :read, f.object.content %>>
  <div class="row module_fields">
    <%= f.hidden_field :actable_type, value: 'Modulee' %>
    <%= f.hidden_field :parent_id %>

    <div class="form-group col-md-5">
      <%= f.label :name, class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group col-md-2">
      <%= link_to_remove_association "<span class='glyphicon glyphicon-minus' aria-hidden='true'></span>".html_safe, f, class: "remove_fields btn btn-sm btn-danger", data: { confirm: 'Are you sure?' }, wrapper_class: 'module_fields'  %>
    </div>
  </div>
</div>

app/views/admin/products/_modulee.html.haml
.panel.panel-default
  .panel-heading
    .h4
      = link_to modulee.title, admin_product_modulee_path(@product, modulee.actable_id)
      - if can? :manage, modulee.specific
        .pull-right
          .btn.btn-default.btn-sm
            = link_to 'Edit', edit_admin_product_modulee_path(@product, modulee.actable_id)

  .panel-body
    .row
      .col-md-12
        .pull-right
          Add:
          .btn.btn-default.btn-sm
            Submodule
          .btn.btn-default.btn-sm
            = link_to('HTML', new_admin_product_html_path(@product, content_id: modulee.id))
          .btn.btn-default.btn-sm
            = link_to('Quiz', new_admin_product_quiz_path(@product, content_id: modulee.id))
          .btn.btn-default.btn-sm
            = link_to('Flashcard', new_admin_product_flashcard_path(@product, content_id: modulee.id))
          .btn.btn-default.btn-sm
            = link_to('Media', new_admin_product_media_path(@product, content_id: modulee.id))
    %br
    %ul.sortable
      / Re-order by :row_order so that all the children specific to modulee are in order
      - modulee.children.order(:row_order).each do |child|
        %li{ "data-content-id": child.id }
          = render partial: child.actable_type.downcase, object: child
/ - if !modulee.parent
/   .pull-right
/     .btn.btn-default
/       = link_to('Add Module', new_admin_product_modulee_path(@product))

app/views/admin/products/_quiz.html.haml
.panel.panel-default
  .panel-heading
    = link_to quiz.title, admin_product_quiz_path(@product, quiz.actable_id)
    .pull-right
      .btn.btn-default.btn-xs
        = link_to('edit', edit_admin_product_quiz_path(@product, quiz.actable_id))
  .panel-body
    quiz details go here

app/views/admin/products/_video_fields.html.erb
<% f.object = f.object.specific if f.object.specific.instance_of? Video %>

<div class="col-md-12" style=<%= "display: hidden".html_safe if cannot? :read, f.object.content %>>
  <div class="row video_fields">
    <%= f.hidden_field :actable_type, value: 'Video' %>
    <%= f.hidden_field :parent_id %>

    <div class="form-group col-md-5">
      <%= f.label :name, class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group col-md-5">
      <%= f.label :url, class: 'control-label' %>
      <%= f.text_field :url, class: 'form-control' %>
    </div>
    
    <div class="form-group col-md-2">
      <%= link_to_remove_association "<span class='glyphicon glyphicon-minus' aria-hidden='true'></span>".html_safe, f, class: "remove_fields btn btn-sm btn-danger", data: { confirm: 'Are you sure?' }, wrapper_class: 'video_fields'  %>
    </div>
  </div>
</div>

app/views/admin/products/edit.html.haml
.h3
  Editing Product

= render 'form', product: @product, content: @contents

app/views/admin/products/index.html.erb
<h3>Products</h3>

<% if @products.present? %>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Title</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product.title, admin_product_path(product), class: 'btn-link' %></td>
          <td>
          <div class="btn-group">
            <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Actions <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to 'View', admin_product_path(product) %></li>
              <% if can? :update, product %>
                <li><%= link_to 'Edit', edit_admin_product_path(product) %></li>
              <% end %>
              <% if can? :destroy, product %>
                <li><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <% end %>
            </ul>
          </div>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
    <p class="well">No records found.</p>
<% end %>
<br>

<%= link_to 'New Product', new_admin_product_path, class: 'btn btn-sm btn-success' if can? :manage, @product %> <%= link_to 'Back', dashboard_path, class: 'btn btn-sm btn-primary' %>

app/views/admin/products/new.html.haml
.h3
  New Product

= render 'form', product: @product