config/routes.rb
  Rails.application.routes.draw do
  root 'dashboard#index'

  get '/admin', to: 'admin/users#index'
  get '/dashboard', to: 'dashboard#index'

  #page
  get 'page/home'
  get 'page/about'
  get 'page/contact'

  #diagnostics
  get 'healthcheck', to: 'diagnostics#healthcheck'

  # Admin
  namespace :admin do
      resources :users do
        member do
          get 'get_user_roles'
        end
      end

      resources :products do
        post 'import'
        resources :contributions, shallow: true do
          collection do

            post 'permissions'
            post 'update_permissions'
            post 'destroy_permissions'
          end
        end

        resources :modulees, path: 'modules'
        resources :flashcards do
          member do
            get 'update_flashcard_item_position'
          end
        end
        resources :htmls, path: 'html'
        resources :quizzes do
          get 'download'
          post 'upload'
        end
        resources :media
      end

      resources :contents do
        collection do
          get 'update_content_position'
        end

        post 'usercontentssave'
        post 'usercontentsupdate'
        resources :contributions, shallow: true do
          collection do
            post 'permissions'
            post 'update_permissions'
            post 'destroy_permissions'

          end
        end

      end

      resources :roles, only: [:show]
  end

  resources :products, only: [:index, :show]

  # Devise
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  # Ckeditor
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/user.rb
class User < ApplicationRecord
  ADMIN = 'Admin'
  PRODUCT_MANAGER = 'Product Manager'
  CONTENT_CONTRIBUTOR = 'Content Contributor'
  INSTRUCTOR = 'Instructor'

  has_ancestry
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :permissions, dependent: :destroy
  has_many :products, through: :permissions

  has_many :user_subscriptions, dependent: :destroy
  has_many :subscribed_products, through: :user_subscriptions, class_name: 'Product', foreign_key: :product_id, source: :product

  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles

  validates :username, presence: true, uniqueness: true

  scope :product_managers, -> { joins(:roles).where('roles.name = ?', PRODUCT_MANAGER) }
  scope :admins, -> { joins(:roles).where('roles.name = ?', ADMIN) }
  scope :non_admins, -> { joins(:roles).where('roles.name != ?', ADMIN) }

  def self.all_except(user)
    where.not(id: user).collect { |u| u if u.roles.pluck(:name).exclude? 'Admin' }.compact
  end

  def has_role?(role)
    if role.instance_of? Array
      role = role.collect { |r| r.to_s.split('_').join(' ').titleize }
      (roles.pluck(:name) & role).empty?
    else
      role.to_s.to_i > 0 ? (roles.pluck(:id).include? role.to_i) : (roles.pluck(:name).include? role.to_s.split('_').join(' ').titleize)
    end
  end

  def can_contribute_to_product?(product_id)
    has_role?(CONTENT_CONTRIBUTOR) && !existing_contributors_for_product(product_id).include?(self.id)
  end

  def is_admin?
    is_type?("Admin")
  end

  def is_product_manager?
    is_type?("Product Manager")
  end

  def is_content_manager?
    is_type?("Content Manager")
  end

  def is_content_contributor?
    is_type?("Content Contributor")
  end

  def is_instructor?
    is_type?("Instructor")
  end

  private

  def is_type? type
    self.roles.map(&:name).include?(type) ? true : false
  end

  # Get contributors list for a certain product
  def existing_contributors_for_product(product_id)
    contributions.where(product_id: product_id)
    .select(:user_id).distinct.pluck(:user_id)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  skip_authorize_resource :only => [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  	@users = User.all
  end

  def show
  end

  def new
    @user = User.new
    if current_user.is_admin?
      @roles = Role.all.pluck(:name)
    elsif current_user.is_product_manager?
      @roles = Role.where(name: [User::PRODUCT_MANAGER, User::CONTENT_CONTRIBUTOR]).pluck(:name)
    end
  end

  def edit
    @user_roles = @user.roles.map(&:name)
    if current_user.is_admin?
      @roles = Role.all.map(&:name)
      @value = false
    elsif current_user.is_product_manager?
      @roles = Role.where(:name=>['Content Contributor','Instructor']).pluck(:name)
      @value = true
    else
      @value = true
    end
  end

  def create
    @user = User.new(user_params)
    @user.roles = roles

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_url(@user), notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    # New to-be-added user roles
    @user.user_roles = roles.collect { |r| UserRole.find_or_create_by(user_id: @user.id, role_id: r.id) }

    respond_to do |format|
      if (password_unchanged? && @user.update_without_password(user_params)) || @user.update(user_params)
        format.html { redirect_to admin_user_url(@user), notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
    end
  end

  def get_user_roles
    user_id = params[:id].to_i if params[:id].present?
    
    roles = User.find(user_id).roles if user_id > 0
    roles = roles.pluck(:id, :name) if roles.count > 0

    render json: roles || []
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation).tap do |whitelisted|
      end
    end

    def roles
      params[:roles].collect { |name| Role.find_by_name(name) }.compact unless params[:roles].blank?
    end

    def password_unchanged?
      user_params[:password].blank?
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 #before_action :configure_sign_up_params, only: [:create]
 before_action :configure_sign_up_params, only: [:create]
 before_action :configure_account_update_params, only: [:update]
 before_action :configure_account_update_params, if: :devise_controller?
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
   #def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :password, :password_confirmation])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
    #params.require(:user).permit(:username, :email, :password, :password_confirmation,:current_password)
     devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation,:current_password])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
 before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   #def create
  #
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :configure_sign_in_params, only: [:create]
  before_action :set_user, only: [:show]

  def index
  end

  def show
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
  end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
.row
  = form_for [:admin, @user], html: { class: 'form col-md-6' } do |f|
    - if user.errors.any?
      #error_explanation
        .h2
          = pluralize(user.errors.count, "error") << "prohibited this user from being saved:"

        %ul
          = user.errors.full_messages.each do |message|
            %li
              = message

    // TODO: Find a better way to do this disabling
    .form-group
      = f.label :username, class: 'control-label' 
      = f.text_field :username, class: 'form-control', :disabled=>@value 

    .form-group
      = f.label :email, class: 'control-label' 
      = f.email_field :email, class: 'form-control', :disabled=>@value

    .form-group
      = f.label :password, class: 'control-label'
      = "<i>(leave blank if you don't want to change it)</i><br/>".html_safe if params[:action] == 'edit' 
      = f.password_field :password, autocomplete: "off", class: 'form-control' 

    .form-group
      = f.label :password_confirmation, class: 'control-label', :disabled=>@value
      = f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' ,:disabled=>@value

    .form-group
      = f.label :roles, class: 'control-label' 
      = select_tag :roles, options_for_select(@roles, @user_roles), multiple: true, prompt: "Default", class: 'form-control'  
    
    .form-group
      = f.submit class: 'btn btn-sm btn-success'

app/views/admin/users/_products.html.erb
<% if products.present? %>
  <% products.each do |product| %>
    <% if can? :update, product %>
      <div class="row">
        <div class="form-group col-md-6">
          <div class="row">
            <label class="col-md-6 control-label"><%= "#{product.title}".html_safe %></label>
            <div class="col-md-6">
              <% if form %>
                <%= hidden_field_tag 'product_ids[]', product.id %>
                <%= select_tag 'role_ids[]', options_for_select(user.roles.map(&:name), user.user_products.role(product.id)), prompt: 'None', class: 'form-control' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/admin/users/edit.html.erb
<h3>Editing User</h3>


<%= render 'form', user: @user %>

<%= link_to 'Show', admin_user_path(@user), class: 'btn btn-sm btn-info' %>
<%= link_to 'Back', admin_users_path, class: 'btn btn-sm btn-primary' %>

app/views/admin/users/index.html.haml
.h3 Users

- if @users.present?
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Role
        %th
    %tbody
      - @users.each do |user|
        - if can? :read, User
          %tr 
            %td
              = link_to user.username, admin_user_path(user), class: 'btn-link'
            %td
              = user.email
            %td
              = user.roles.collect {|role| link_to role.name, admin_role_path(role), class: 'btn-link' }.join(', ').html_safe unless user.roles.blank?
            %td 
              .btn-group
                %button{ type: 'button', class: 'btn btn-primary btn-sm dropdown-toggle', data: { toggle: 'dropdown' }, aria: { haspopup: true, expanded: false } }
                  Actions
                  %span.caret
                %ul.dropdown-menu
                  - if can? :read, user
                    %li
                      = link_to 'View', admin_user_path(user)
                  - if can? :manage, User
                    %li
                      = link_to 'Edit', edit_admin_user_path(user)
                    %li
                      = link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }
- else
  %p.well
    No records found

%br
- if can? :manage, @user
  = link_to 'New User', new_admin_user_path, class: 'btn btn-sm btn-success'

= link_to 'Back', dashboard_path, class: 'btn btn-sm btn-primary'

app/views/admin/users/new.html.erb
<h3>New User</h3>

<%= render 'form', user: @user %>

<%= link_to 'Back', admin_users_path, class: 'btn btn-sm btn-primary' %>

app/views/admin/users/show.html.haml
.h3 Account Details
%p
  %strong Username:
  = @user.username
  
  %br
  %br
  
  %strong Email:
  = @user.email

  - if @user.roles.present?
    %br
    %br
    %strong Roles:
    = @user.roles.map(&:name).join(', ')

%br
.row
  .col-md-12
    = link_to 'Edit', edit_admin_user_path(@user), class: 'btn btn-sm btn-success' if can? :manage, @user
    = link_to 'Back', admin_users_path, class: 'btn btn-sm btn-primary'